blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/Datalove/DataLove/discussions
    about: Please use discussions for questions and general discussions
